apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minikube
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: pv-mysql
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv-minikube/
