apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minikube-wp
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  storageClassName: pv-wordpress
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/pv-minikube-wp/
